steps:
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "build",
      "-t", "asia-northeast1-docker.pkg.dev/$PROJECT_ID/runtime-bump-bot/image:${SHORT_SHA}",
      "--build-arg",
      "PERSONAL_ACCESS_TOKEN=$$PERSONAL_ACCESS_TOKEN",
       "."
    ]
    secretEnv: ["PERSONAL_ACCESS_TOKEN"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia-northeast1-docker.pkg.dev/${PROJECT_ID}/runtime-bump-bot/image:${SHORT_SHA}"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: [
      "run",
      "jobs",
      "deploy",
      "runtime-bump-bot",
      "--image",
      "asia-northeast1-docker.pkg.dev/${PROJECT_ID}/runtime-bump-bot/image:${SHORT_SHA}",
      "--region",
      "asia-northeast1",
    ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: [
      "scheduler",
      "jobs",
      "create",
      "http",
      "runtime-bump-bot-schedule",
      "--location",
      "asia-northeast1",
      "--schedule='cron(0 0 * * 1)'",
      "--uri='https://asia-northeast1-run.googleapis.com/apis/run.googleapis.com/v1/namespaces/${PROJECT_ID}/jobs/runtime-bump-bot:run'",
      "--http-method",
      "POST",
      "--oauth-service-account-email",
      "${PROJECT_NUMBER}-compute@developer.gserviceaccount.com",
      "--region",
      "asia-northeast1",
    ]

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/PERSONAL_ACCESS_TOKEN/versions/latest
    env: PERSONAL_ACCESS_TOKEN

images:
  - "asia-northeast1-docker.pkg.dev/${PROJECT_ID}/runtime-bump-bot/image:${SHORT_SHA}"
